# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - allow:
      - dependency-type: 'direct'
    commit-message:
      include: 'scope'
      prefix: 'npm'
    directory: '/'
    labels:
      - 'dependency'
      - 'automerge'
    open-pull-requests-limit: 5
    package-ecosystem: 'npm'
    schedule:
      interval: 'daily'
    versioning-strategy: 'lockfile-only'
